apiVersion: flink.lyft.com/v1alpha1
kind: FlinkApplication
metadata:
  name: flink-example-11
  namespace: flink
  annotations:
      iam.amazonaws.com/role: "arn:aws:iam::173840052742:role/modelbuilderagentbatchworker-staging"
spec:
  image: 173840052742.dkr.ecr.us-east-1.amazonaws.com/streamingspeeds:fdec74a5cb3b5d2a9cae793aba98350fca39eba2
  job_manager_config:
    job_manager_count: 2
    env_config:
      env:
        x: y
      envFrom:
        - configMapRef:
            name: flink-staging-ha-config
  task_manager_config:
    task_manager_count: 2
    env_config:
      envFrom:
        - configMapRef:
            name: flink-staging-ha-config
flink_job:
  jar_name: "streamingspeeds-1.0.0-SNAPSHOT.jar"
  parallelism: 2
  entry_class: "com.lyft.streamingspeeds.StreamingSpeedsClient"
deployment_mode: Single
