# This file needs to be removed before we open source.
apiVersion: flink.k8s.io/v1alpha1
kind: FlinkApplication
metadata:
  name: flink-speeds-working-stats
  namespace: flink
  annotations:
    iam.amazonaws.com/role: ""
  labels:
    app: "app-name"
    environment: "staging"
spec:
  image: 100.dkr.ecr.us-east-1.amazonaws.com/abc:xyz
  flinkJob:
    jarName: "name.jar"
    parallelism: 10
  deploymentMode: Single
