sudo: required
language: go
go:
  - "1.10"
services:
  - docker
jobs:
  include:
    - stage: test
      name: docker build and push
      install: true
      script: make dockerhub_push
    - stage: test
      name: unit tests
      install: make install
      script: make test_unit
