sudo: required
language: go
dist: xenial
go:
  - "1.10"
services:
  - docker
jobs:
  include:
    - stage: build
      name: docker build and push
      install: true
      script: make dockerhub_push
    - stage: build
      name: unit tests
      install: make install
      script: make test_unit
    - stage: integ-test
      name: integration tests
      install: integ/install.sh
      before_script: integ/setup.sh
      script:
        - integ/run_tests.sh
