required = [
  "sigs.k8s.io/controller-runtime/pkg/client/config",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "^0.1.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.2"
