---
kind: ConfigMap
apiVersion: v1
metadata:
  name: flink-operator-config
data:
  development: |-
    operator:
      containerNameFormat: "%s-unknown"
    logger:
      show-source: true
      level: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flinkk8soperator
  namespace: default
  labels:
    app: flinkk8soperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flinkk8soperator
  template:
    metadata:
      labels:
        app: flinkk8soperator
        app.kubernetes.io/name: flinkk8soperator
        app.kubernetes.io/version: 0.0.1
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: flink-operator-config
          items:
          - key: development
            path: config.yaml
      containers:
      - name: flinkk8soperator
        image: lyft/flinkk8soperator:${sha}
        env:
        - name: OPERATOR_NAME
          value: flinkk8soperator
        command:
          - flinkoperator
        args:
          - "--config"
          - "/etc/flinkk8soperator/config/config.yaml"
        ports:
          - containerPort: 10254
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.2"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/flinkk8soperator/config
      imagePullSecrets:
        - name: dockerhub
