# Create a ClusterRole for flytepropeller
# https://kubernetes.io/docs/admin/authorization/rbac/
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flinkk8soperator
rules:
#Allow RO access to PODS
 - apiGroups:
    - ""
   resources:
    - pods
   verbs:
    - get
    - list
    - watch
#Allow Event recording access
 - apiGroups:
    - ""
   resources:
    - events
   verbs:
    - create
    - update
    - delete
    - patch
#Allow Access All plugin objects
 - apiGroups:
    - "*"
   resources:
    - "*"
   verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
#Allow Access to CRD
 - apiGroups:
   - apiextensions.k8s.io
   resources:
   - customresourcedefinitions
   verbs:
   - get
   - list
   - watch
   - create
   - delete
   - update
#Allow Access to all resources under flink.lyft.com
 - apiGroups:
   - flink.lyft.com
   resources:
   - flinkapplications
   verbs:
   - get
   - list
   - watch
   - create
   - update
   - delete
   - patch
---
# Create a Service Account for flinkk8soperator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flinkk8soperator
  namespace: flinkoperator
---
# Create a binding from Role -> ServiceAccount
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flinkk8soperator
  namespace: flinkoperator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flinkk8soperator
subjects:
- kind: ServiceAccount
  name: flinkk8soperator
  namespace: flinkoperator

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: flink-operator-config
  namespace: flinkoperator
data:
  # this will need to be templatized
  staging: |-
    ingressUrlFormat: "{{$jobCluster}}.ingress.flinkstaging.us-east-1.k8s.lyft.net"
    containerNameFormat: "%s-unknown"
    statemachineStalenessDuration: 10m
---

# Create the actual deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flinkk8soperator
  namespace: flinkoperator
  labels:
    app: flinkk8soperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flinkk8soperator
  template:
    metadata:
      labels:
        app: flinkk8soperator
        app.kubernetes.io/name: flinkk8soperator
        app.kubernetes.io/version: 0.0.1
    spec:
      serviceAccountName: flinkk8soperator
      imagePullSecrets:
      - name: dockerhub
      volumes:
      - name: config-volume
        configMap:
          name: flink-operator-config
          items:
          - key: staging
            path: flinkk8soperator_config.yaml
      containers:
      - name: flinkk8soperator
        image: docker.io/lyft/flinkk8soperator:cc9fb97cb92a595fda75fbcbe7118dd9633e7cba
        env:
        - name: OPERATOR_NAME
          value: flinkk8soperator
        imagePullPolicy: Always
        ports:
          - containerPort: 10254
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
          limits:
            memory: "8G"
            cpu: "8"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/flinkk8soperator/config
